### ISSUE TITLE
Confirm Mozilla PDX has switched to Zoom

### ISSUE THREAD

**Issue by aaronpk** [indieweb/2019.indieweb.org#58]
if Moz has switched to Zoom in all their rooms then we can use our IndieWeb Zoom account with their hardware and avoid bringing iPads and such.

**Comment by aaronpk** [comment]
Following up, we'll test this out Friday during the Organizers' meeting. I will have the iPad kit ready to go for Saturday if that doesn't work.

**Comment by dshanske** [comment]
Confirmed
