### ISSUE TITLE
Look for Friday Night Social Event for NYC

### ISSUE THREAD

**Issue by jgmac1106** [indieweb/2019.indieweb.org#86]
Based on new inclusion guidelines the event should not be alcohol centric (sorry Dead Rabbit ) and should have other activities or food as the primary gathering.

**Comment by martymcguire** [comment]
Suggestions from my social network. I can't vouch for most of them, not having been!

* Stone Street (outdoor communal tables with many nearby restaurants to order from)
    * [🔗 TripAdvisor](https://www.tripadvisor.com/Attraction_Review-g60763-d105043-Reviews-Stone_Street_Historic_District-New_York_City_New_York.html), [🔗 City Rover guide](https://cityroverwalks.com/stone-street-nyc/)
    * Challenges
        * outdoor seating may be hit or miss in early Oct.
        * no single vendor to work w/ so sponsorship for food/drink tickets might be tough.
* [Clinton Hall Financial District](https://clintonhallny.com/fidi/)
    * large covered patio with communal tables, table games
    * we've been here for post-IWC food and beverages before
    * largely a bar w/ many beers on tap, but also has food and other options
* [Harry's Italian Financial District](https://www.harrysitalian.com/)
    * Italian restaurant
    * [takes reservations for private events](https://www.harrysitalian.com/events)
* [The Crown](https://www.thecrownnyc.com/)
    * looks like rooftop restaurant and bar at 50 Bowery St
    * online reservation system doesn't take Fri/Sat/Sun reservations
    * can email to make reservations for larger parties. maybe incl Friday?

**Comment by jgmac1106** [comment]
I am digging on Stone Street.
